### ISSUE TITLE
The qpidd-session-max-unacked role breaks Satellite 6.2.8

### ISSUE THREAD

**Issue by PizarroG** [redhat-performance/satellite-tune#20]
Seen in both the Satellite and the Capsules. Commenting out the line

session-max-unacked=100

in /etc/qpid/qpidd.conf and restarting qpidd fixes it.

This setting isn't in the official guide as far as I can tell. And since that's linked one would get the impression that only what's in the guide will be applied. Perhaps it's best to simply remove it.

**Comment by psuriset** [comment]
Thanks @PizarroG  
Disabled it for now.
